# Generated by Django 5.1.1 on 2024-11-02 20:28

import meal_planner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('meal_plan_id', models.CharField(default=meal_planner.models.generate_content_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('meals_structure', models.JSONField(default=dict)),
                ('tags', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('SV', 'Saved')], default='DR', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
