# Generated by Django 5.1.1 on 2024-09-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryassessment',
            name='bmi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dietaryassessment',
            name='tdee',
            field=models.FloatField(default=0.0),
        ),
    ]
