# Generated by Django 5.1.1 on 2024-09-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mealplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='recipe',
            new_name='recipe_id',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'recipe_id')},
        ),
    ]
