# Generated by Django 5.1.1 on 2024-09-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_recipe_rating_recipe_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'recipe')},
        ),
    ]
