# Generated by Django 5.1.1 on 2024-10-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_recipe_id_rating_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_levels',
            field=models.FloatField(default=1.55),
        ),
    ]
