# Generated by Django 5.1.1 on 2024-10-17 18:18

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_activity_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcontent',
            name='content_main',
            field=models.TextField(default='Test'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='duration',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=users.models.recipe_file_path),
        ),
    ]
