# Generated by Django 5.1.1 on 2024-10-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_educationalcontent_content_main_recipe_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bmi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='tdee',
            field=models.FloatField(default=0.0),
        ),
    ]
