# Generated by Django 5.1.1 on 2024-10-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_bmi_user_tdee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietaryassessment',
            name='goals',
        ),
    ]
