# Generated by Django 5.1.1 on 2024-10-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_dietaryassessment_goals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
