# Generated by Django 5.1.1 on 2024-10-23 09:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_mealplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('dairy-free', 'Dairy-Free'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('high-protein', 'High-Protein'), ('low-protein', 'Low-Protein'), ('low-carb', 'Low-Carb'), ('nut-free', 'Nut_Free'), ('shellfish-free', 'Shellfish-Free'), ('lactose-free', 'Lactose-Free'), ('egg-free', 'Egg-Free'), ('peanut-free', 'Peanut-Free'), ('soy_free', 'Soy-Free'), ('low-sugar', 'Low-Sugar'), ('spicy', 'Spicy'), ('sweet', 'Sweet'), ('savory', 'Savory'), ('organic', 'Organic'), ('high-fiber', 'High-Fiber'), ('high-fat', 'High-Fat'), ('moderate-carbs', 'Moderate-Carbs'), ('low-fat', 'Low-Fat'), ('moderate-protein', 'Moderate-Protein'), ('balance', 'Balanced')], max_length=50), size=5),
        ),
    ]
