# Generated by Django 5.1.1 on 2024-10-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryassessment',
            name='cuisine_preference',
            field=models.JSONField(default=dict),
        ),
    ]
